### ISSUE TITLE
I checkout a new branch called 'chinese' on my fork

### ISSUE THREAD

**Issue by Iamlars** [peterkokot/awesome-jquery#7]
Hi! 
### Awesome jQuery is an awesome repository
So I create a new branch called 'chinese' on my fork, it is translate Awesome jQuery to simplified Chinese,the link is [I'm a link](https://github.com/Iamlars/awesome-jquery/tree/chinese),it is be allowed?

**Comment by peterkokot** [comment]
Hello, @Iamlars 
This is of course OK. Great work. :+1: I've added your translation via d8de831d146626c9df916dcdd6d3ee853a76089c

If you have any other requests or suggestions, just ask or reopen this ticket.
